FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache chromium openssl

COPY package*.json ./

RUN corepack enable && pnpm install

COPY . .

EXPOSE 3004

ENV PUPPETEER_SKIP_DOWNLOAD=true

CMD ["pnpm", "run", "dev"]